// Architected by Khalid Hasan Limon
package com.example.ui

import android.content.ContentValues
import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.net.Uri
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import com.example.data.AuditLogEntry
import com.example.data.InventoryItem
import java.io.File
import java.io.FileOutputStream
import java.io.OutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object ExportEngine {

    fun exportToCSV(
        context: Context,
        items: List<InventoryItem>,
        logs: List<AuditLogEntry>
    ): String {
        val sdf = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault())
        val timestamp = sdf.format(Date())
        val fileName = "Polwel_Export_$timestamp.csv"
        
        val csvBuilder = StringBuilder()
        
        // 1. App Header & Attribution
        csvBuilder.append("Polwel Inventory Enterprise Report\n")
        csvBuilder.append("Developed by Khalid Hasan Limon\n")
        csvBuilder.append("Generated Time,${SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(Date())}\n")
        csvBuilder.append("Export Footprint,Generated by Polwel Inventory | Developed by Khalid Hasan Limon\n\n")
        
        // 2. Summary stats
        val totalItems = items.size
        val totalStock = items.sumOf { it.currentStock }
        val totalValuation = items.sumOf { it.currentStock * it.cost }
        csvBuilder.append("SUMMARY STATS\n")
        csvBuilder.append("Total Unique SKUs,$totalItems\n")
        csvBuilder.append("Total Current Stock,$totalStock\n")
        csvBuilder.append("Total Valuation,TK ${String.format(Locale.US, "%.2f", totalValuation)}\n\n")
        
        // 3. Inventory Table
        csvBuilder.append("CURRENT INVENTORY\n")
        csvBuilder.append("Item ID,Name,SKU,Category,Current Stock,Unit Cost,Total Value\n")
        for (item in items) {
            val totalValue = item.currentStock * item.cost
            csvBuilder.append("${item.itemId},\"${item.name}\",\"${item.sku}\",\"${item.category}\",${item.currentStock},${item.cost},${String.format(Locale.US, "%.2f", totalValue)}\n")
        }
        csvBuilder.append("\n")
        
        // 4. Audit Log Table
        csvBuilder.append("AUDIT LOG TRADING TRANSACTION LOGS\n")
        csvBuilder.append("Log ID,Item ID,Product Name,Type (IN/OUT),Quantity Changed,Details,Timestamp\n")
        val logSdf = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault())
        for (log in logs) {
            val dateStr = logSdf.format(Date(log.timestamp))
            val detailSafe = log.details.replace("\"", "\"\"")
            csvBuilder.append("${log.logId},${log.itemId},\"${log.productName}\",${log.transactionType},${log.quantityChanged},\"$detailSafe\",\"$dateStr\"\n")
        }
        
        val content = csvBuilder.toString()
        val fileUriString = writeToDownloads(context, fileName, "text/csv", content.toByteArray())
        return fileUriString ?: "Export failed"
    }

    fun exportToPDF(
        context: Context,
        items: List<InventoryItem>,
        periodLogs: List<AuditLogEntry> = emptyList(),
        periodTitle: String = "All Time"
    ): String {
        val sdf = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault())
        val timestamp = sdf.format(Date())
        val fileName = "Polwel_Report_$timestamp.pdf"
        
        val pdfDocument = PdfDocument()
        
        val baseTypeface = Typeface.create(Typeface.SERIF, Typeface.NORMAL)
        val boldTypeface = Typeface.create(Typeface.SERIF, Typeface.BOLD)
        val banglaTypeface = baseTypeface
        val banglaBoldTypeface = boldTypeface
        
        val pageWidth = 595
        val pageHeight = 842
        
        var pageNum = 1
        var pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNum).create()
        var page = pdfDocument.startPage(pageInfo)
        var canvas = page.canvas
        val paint = Paint()
        
        fun drawFooter() {
            paint.color = Color.parseColor("#475569")
            paint.strokeWidth = 0.8f
            paint.style = Paint.Style.STROKE
            canvas.drawLine(20f, (pageHeight - 50).toFloat(), (pageWidth - 20).toFloat(), (pageHeight - 50).toFloat(), paint)
            paint.style = Paint.Style.FILL
            paint.color = Color.parseColor("#64748B")
            paint.textSize = 8.5f
            paint.typeface = banglaTypeface
            canvas.drawText("Generated by Polwel Inventory | Developed by Khalid Hasan Limon", 35f, (pageHeight - 35).toFloat(), paint)
            canvas.drawText("Page $pageNum", (pageWidth - 75).toFloat(), (pageHeight - 35).toFloat(), paint)
        }
        
        fun newPage() {
            drawFooter()
            pdfDocument.finishPage(page)
            pageNum++
            pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNum).create()
            page = pdfDocument.startPage(pageInfo)
            canvas = page.canvas
            canvas.drawColor(Color.WHITE)
        }

        // --- PAGE 1 HEADER ---
        canvas.drawColor(Color.WHITE)
        
        paint.color = Color.BLACK
        paint.style = Paint.Style.STROKE
        paint.strokeWidth = 1f
        canvas.drawRect(20f, 20f, (pageWidth - 20).toFloat(), 130f, paint)
        
        paint.style = Paint.Style.FILL
        paint.color = Color.BLACK
        paint.textSize = 20f
        paint.isAntiAlias = true
        paint.typeface = banglaBoldTypeface
        canvas.drawText("POLWEL INVENTORY REPORT", 30f, 50f, paint)
        
        paint.textSize = 10f
        paint.typeface = banglaTypeface
        canvas.drawText("Report by: Md Rezaul Karim", 30f, 70f, paint)
        
        paint.textSize = 9f
        canvas.drawText("Report Generated: " + SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(Date()) + " | Period: $periodTitle", 30f, 115f, paint)
        
        val totalValuation = items.sumOf { it.currentStock * it.cost }
        paint.color = Color.BLACK
        paint.textSize = 11f
        paint.typeface = boldTypeface
        canvas.drawText("TOTAL VALUE: ৳${String.format(Locale.US, "%.2f", totalValuation)}", (pageWidth - 230).toFloat(), 50f, paint)
        
        paint.typeface = baseTypeface
        paint.textSize = 10f
        canvas.drawText("Total Unique SKUs: ${items.size}", (pageWidth - 230).toFloat(), 75f, paint)
        canvas.drawText("Total Items Instock: ${items.sumOf { it.currentStock }}", (pageWidth - 230).toFloat(), 95f, paint)
        
        // --- ITEMS TABLE ---
        val col1 = 20f
        val col2 = 175f
        val col3 = 275f
        val col4 = 375f
        val col5 = 445f
        val col6 = 510f
        val col7 = (pageWidth - 20).toFloat()
        
        var startY = 150f
        var currentY = startY + 25f
        
        fun drawItemsTableHeader() {
            paint.style = Paint.Style.FILL
            paint.color = Color.BLACK
            paint.textSize = 10f
            paint.typeface = boldTypeface
            
            canvas.drawText("NAME", col1 + 5f, startY + 16f, paint)
            canvas.drawText("SKU", col2 + 5f, startY + 16f, paint)
            canvas.drawText("CATEGORY", col3 + 5f, startY + 16f, paint)
            canvas.drawText("STOCK", col4 + 5f, startY + 16f, paint)
            canvas.drawText("COST", col5 + 5f, startY + 16f, paint)
            canvas.drawText("TOTAL", col6 + 5f, startY + 16f, paint)
            
            paint.style = Paint.Style.STROKE
            paint.strokeWidth = 1f
            canvas.drawLine(col1, startY, col7, startY, paint)
            canvas.drawLine(col1, currentY, col7, currentY, paint)
        }
        
        fun drawItemsTableBorders(bottomY: Float) {
            paint.style = Paint.Style.STROKE
            paint.color = Color.BLACK
            canvas.drawRect(col1, startY, col7, bottomY, paint)
            canvas.drawLine(col2, startY, col2, bottomY, paint)
            canvas.drawLine(col3, startY, col3, bottomY, paint)
            canvas.drawLine(col4, startY, col4, bottomY, paint)
            canvas.drawLine(col5, startY, col5, bottomY, paint)
            canvas.drawLine(col6, startY, col6, bottomY, paint)
        }
        
        drawItemsTableHeader()
        
        for (item in items) {
            if (currentY + 21f > pageHeight - 65f) {
                drawItemsTableBorders(currentY)
                newPage()
                startY = 40f
                currentY = startY + 25f
                drawItemsTableHeader()
            }
            
            paint.style = Paint.Style.FILL
            paint.color = Color.BLACK
            currentY += 21f
            
            paint.typeface = banglaTypeface
            val displayName = if (item.name.length > 20) item.name.substring(0, 17) + "..." else item.name
            canvas.drawText(displayName, col1 + 5f, currentY - 5f, paint)
            canvas.drawText(item.sku, col2 + 5f, currentY - 5f, paint)
            canvas.drawText(item.category, col3 + 5f, currentY - 5f, paint)
            
            if (item.currentStock <= 5) {
                paint.typeface = banglaBoldTypeface
            }
            canvas.drawText(item.currentStock.toString(), col4 + 5f, currentY - 5f, paint)
            paint.typeface = banglaTypeface
            
            canvas.drawText("৳${String.format(Locale.US, "%.2f", item.cost)}", col5 + 5f, currentY - 5f, paint)
            
            val totalValue = item.currentStock * item.cost
            paint.typeface = banglaBoldTypeface
            canvas.drawText("৳${String.format(Locale.US, "%.2f", totalValue)}", col6 + 5f, currentY - 5f, paint)
            
            paint.style = Paint.Style.STROKE
            canvas.drawLine(col1, currentY, col7, currentY, paint)
        }
        drawItemsTableBorders(currentY)
        
        // --- CHART (only on first or next page if it fits) ---
        if (items.isNotEmpty()) {
            if (currentY + 160f > pageHeight - 65f) {
                newPage()
                currentY = 40f
            } else {
                currentY += 20f
            }
            
            val categoryStocks = items.groupBy { it.category }
                .mapValues { it.value.sumOf { item -> item.currentStock } }
                .toList()
                .sortedByDescending { it.second }
                .take(5)
            
            if (categoryStocks.isNotEmpty()) {
                val maxStock = categoryStocks.maxOf { it.second }.toFloat()
                val chartStartY = currentY + 15f
                val chartHeight = 110f
                val chartStartX = 40f
                val chartWidth = (pageWidth - 80).toFloat()
                val maxBarHeight = chartHeight - 20f
                val barSpacing = chartWidth / categoryStocks.size
                val barWidth = barSpacing * 0.5f
                
                paint.style = Paint.Style.FILL
                paint.color = Color.parseColor("#0F172A")
                paint.textSize = 10.5f
                paint.typeface = Typeface.create(Typeface.SERIF, Typeface.BOLD)
                canvas.drawText("CATEGORY STOCK DISTRIBUTION (TOP 5)", chartStartX, chartStartY - 15f, paint)
                
                paint.style = Paint.Style.STROKE
                paint.strokeWidth = 0.5f
                paint.color = Color.parseColor("#E2E8F0")
                for (i in 0..4 step 2) {
                    val gridY = chartStartY + (chartHeight * i / 4)
                    canvas.drawLine(chartStartX, gridY, chartStartX + chartWidth, gridY, paint)
                }
                
                paint.strokeWidth = 1.2f
                paint.color = Color.parseColor("#64748B")
                canvas.drawLine(chartStartX, chartStartY, chartStartX, chartStartY + chartHeight, paint) 
                canvas.drawLine(chartStartX, chartStartY + chartHeight, chartStartX + chartWidth, chartStartY + chartHeight, paint) 
                
                paint.style = Paint.Style.FILL
                for ((idx, categoryPair) in categoryStocks.withIndex()) {
                    val categoryName = categoryPair.first
                    val categoryVal = categoryPair.second
                    
                    val normalizedHeight = if (maxStock > 0f) (categoryVal / maxStock) * maxBarHeight else 0f
                    val startX = chartStartX + (idx * barSpacing) + (barSpacing - barWidth) / 2
                    val topY = chartStartY + chartHeight - normalizedHeight
                    
                    paint.color = Color.parseColor("#38BDF8")
                    canvas.drawRect(startX, topY, startX + barWidth, chartStartY + chartHeight, paint)
                    
                    paint.color = Color.parseColor("#0F172A")
                    paint.textSize = 8.5f
                    paint.typeface = Typeface.create(Typeface.SERIF, Typeface.BOLD)
                    canvas.drawText(categoryVal.toString(), startX + barWidth / 3f, topY - 5f, paint)
                    
                    paint.typeface = Typeface.create(Typeface.SERIF, Typeface.NORMAL)
                    paint.color = Color.parseColor("#475569")
                    val shortName = if (categoryName.length > 12) categoryName.substring(0, 10) + ".." else categoryName
                    canvas.drawText(shortName, startX, chartStartY + chartHeight + 14f, paint)
                }
                currentY = chartStartY + chartHeight + 30f
            }
        }
        
        // --- LOGS TABLE ---
        if (periodLogs.isNotEmpty()) {
            newPage()
            
            paint.color = Color.BLACK
            paint.style = Paint.Style.FILL
            paint.textSize = 16f
            paint.typeface = banglaBoldTypeface
            canvas.drawText("AUDIT TRANSACTION LOGS ($periodTitle)", 40f, 60f, paint)
            
            val logCol1 = 20f
            val logCol2 = 110f
            val logCol3 = 210f
            val logCol4 = 260f
            val logCol5 = 310f
            val logCol6 = (pageWidth - 20).toFloat()
            
            var logStartY = 100f
            var logCurrentY = logStartY + 25f
            
            fun drawLogsTableHeader() {
                paint.color = Color.BLACK
                paint.style = Paint.Style.STROKE
                paint.strokeWidth = 1f
                canvas.drawLine(logCol1, logStartY, logCol6, logStartY, paint)
                
                paint.style = Paint.Style.FILL
                paint.textSize = 10f
                paint.typeface = boldTypeface
                canvas.drawText("DATE/TIME", logCol1 + 5f, logStartY + 16f, paint)
                canvas.drawText("PRODUCT", logCol2 + 5f, logStartY + 16f, paint)
                canvas.drawText("TYPE", logCol3 + 5f, logStartY + 16f, paint)
                canvas.drawText("QTY", logCol4 + 5f, logStartY + 16f, paint)
                canvas.drawText("DETAILS", logCol5 + 5f, logStartY + 16f, paint)
                
                paint.style = Paint.Style.STROKE
                canvas.drawLine(logCol1, logCurrentY, logCol6, logCurrentY, paint)
            }
            
            fun drawLogsTableBorders(bottomY: Float) {
                paint.style = Paint.Style.STROKE
                paint.color = Color.BLACK
                canvas.drawRect(logCol1, logStartY, logCol6, bottomY, paint)
                canvas.drawLine(logCol2, logStartY, logCol2, bottomY, paint)
                canvas.drawLine(logCol3, logStartY, logCol3, bottomY, paint)
                canvas.drawLine(logCol4, logStartY, logCol4, bottomY, paint)
                canvas.drawLine(logCol5, logStartY, logCol5, bottomY, paint)
            }
            
            drawLogsTableHeader()
            
            val logSdf = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault())
            
            for (log in periodLogs) {
                if (logCurrentY + 22f > pageHeight - 65f) {
                    drawLogsTableBorders(logCurrentY)
                    newPage()
                    logStartY = 40f
                    logCurrentY = logStartY + 25f
                    drawLogsTableHeader()
                }
                
                paint.style = Paint.Style.FILL
                paint.color = Color.BLACK
                logCurrentY += 22f
                
                paint.typeface = banglaTypeface
                paint.textSize = 10f
                val dateStr = logSdf.format(Date(log.timestamp))
                canvas.drawText(dateStr, logCol1 + 5f, logCurrentY - 6f, paint)
                
                val shortSku = if (log.productName.length > 15) log.productName.substring(0, 13) + ".." else log.productName
                canvas.drawText(shortSku, logCol2 + 5f, logCurrentY - 6f, paint)
                
                paint.color = if (log.transactionType == "IN") Color.parseColor("#059669") else Color.parseColor("#E11D48")
                canvas.drawText(log.transactionType, logCol3 + 5f, logCurrentY - 6f, paint)
                
                paint.color = Color.BLACK
                val qtySign = if (log.transactionType == "IN") "+" else "-"
                canvas.drawText("$qtySign${log.quantityChanged}", logCol4 + 5f, logCurrentY - 6f, paint)
                
                // Allow longer details since width is ~265
                val detailsStr = if (log.details.isBlank()) "None" else if (log.details.length > 55) log.details.substring(0, 52) + "..." else log.details
                canvas.drawText(detailsStr, logCol5 + 5f, logCurrentY - 6f, paint)
                
                paint.style = Paint.Style.STROKE
                canvas.drawLine(logCol1, logCurrentY, logCol6, logCurrentY, paint)
            }
            drawLogsTableBorders(logCurrentY)
        }
        
        drawFooter()
        pdfDocument.finishPage(page)
        
        val fileUriString = writePdfDocumentToDownloads(context, pdfDocument, fileName)
        pdfDocument.close()
        
        return fileUriString ?: "Export failed"
    }

    private fun writeToDownloads(
        context: Context,
        fileName: String,
        mimeType: String,
        data: ByteArray
    ): String? {
        if (BackupRestoreManager.hasStoragePermission(context)) {
            BackupRestoreManager.initializeDirectories()
            val targetFile = File(BackupRestoreManager.reportsDir, fileName)
            try {
                val out = FileOutputStream(targetFile)
                out.write(data)
                out.close()
                return targetFile.absolutePath
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }
        
        val resolver = context.contentResolver
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            val contentValues = ContentValues().apply {
                put(MediaStore.MediaColumns.DISPLAY_NAME, fileName)
                put(MediaStore.MediaColumns.MIME_TYPE, mimeType)
                put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS)
            }
            try {
                val uri = resolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, contentValues)
                if (uri != null) {
                    val outputStream: OutputStream? = resolver.openOutputStream(uri)
                    if (outputStream != null) {
                        outputStream.write(data)
                        outputStream.close()
                        return uri.toString()
                    }
                }
            } catch (e: Exception) {
                e.printStackTrace()
            }
        } else {
            // Android 9 and lower
            val downloadsDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
            if (!downloadsDir.exists()) {
                downloadsDir.mkdirs()
            }
            val targetFile = File(downloadsDir, fileName)
            try {
                val out = FileOutputStream(targetFile)
                out.write(data)
                out.close()
                return Uri.fromFile(targetFile).toString()
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }
        return null
    }

    private fun writePdfDocumentToDownloads(
        context: Context,
        pdfDocument: PdfDocument,
        fileName: String
    ): String? {
        if (BackupRestoreManager.hasStoragePermission(context)) {
            BackupRestoreManager.initializeDirectories()
            val targetFile = File(BackupRestoreManager.reportsDir, fileName)
            try {
                val out = FileOutputStream(targetFile)
                pdfDocument.writeTo(out)
                out.close()
                return targetFile.absolutePath
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }

        val resolver = context.contentResolver
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            val contentValues = ContentValues().apply {
                put(MediaStore.MediaColumns.DISPLAY_NAME, fileName)
                put(MediaStore.MediaColumns.MIME_TYPE, "application/pdf")
                put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS)
            }
            try {
                val uri = resolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, contentValues)
                if (uri != null) {
                    val outputStream: OutputStream? = resolver.openOutputStream(uri)
                    if (outputStream != null) {
                        pdfDocument.writeTo(outputStream)
                        outputStream.close()
                        return uri.toString()
                    }
                }
            } catch (e: Exception) {
                e.printStackTrace()
            }
        } else {
            val downloadsDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
            if (!downloadsDir.exists()) {
                downloadsDir.mkdirs()
            }
            val targetFile = File(downloadsDir, fileName)
            try {
                val out = FileOutputStream(targetFile)
                pdfDocument.writeTo(out)
                out.close()
                return Uri.fromFile(targetFile).toString()
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }
        return null
    }
}
