// Architected by Khalid Hasan Limon
package com.example.ui

import android.content.ContentValues
import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.net.Uri
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import com.example.data.AuditLogEntry
import com.example.data.InventoryItem
import java.io.File
import java.io.FileOutputStream
import java.io.OutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object ExportEngine {

    fun exportToCSV(
        context: Context,
        items: List<InventoryItem>,
        logs: List<AuditLogEntry>
    ): String {
        val sdf = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault())
        val timestamp = sdf.format(Date())
        val fileName = "Polwel_Export_$timestamp.csv"
        
        val csvBuilder = StringBuilder()
        
        // 1. App Header & Attribution
        csvBuilder.append("Polwel Inventory Enterprise Report\n")
        csvBuilder.append("Developed by Khalid Hasan Limon\n")
        csvBuilder.append("Generated Time,${SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(Date())}\n")
        csvBuilder.append("Export Footprint,Generated by Polwel Inventory | Khalid Hasan Limon\n\n")
        
        // 2. Summary stats
        val totalItems = items.size
        val totalStock = items.sumOf { it.currentStock }
        val totalValuation = items.sumOf { it.currentStock * it.cost }
        csvBuilder.append("SUMMARY STATS\n")
        csvBuilder.append("Total Unique SKUs,$totalItems\n")
        csvBuilder.append("Total Current Stock,$totalStock\n")
        csvBuilder.append("Total Valuation,TK ${String.format(Locale.US, "%.2f", totalValuation)}\n\n")
        
        // 3. Inventory Table
        csvBuilder.append("CURRENT INVENTORY\n")
        csvBuilder.append("Item ID,Name,SKU,Category,Current Stock,Unit Cost,Total Value\n")
        for (item in items) {
            val totalValue = item.currentStock * item.cost
            csvBuilder.append("${item.itemId},\"${item.name}\",\"${item.sku}\",\"${item.category}\",${item.currentStock},${item.cost},${String.format(Locale.US, "%.2f", totalValue)}\n")
        }
        csvBuilder.append("\n")
        
        // 4. Audit Log Table
        csvBuilder.append("AUDIT LOG TRADING TRANSACTION LOGS\n")
        csvBuilder.append("Log ID,Item ID,Product Name,Type (IN/OUT),Quantity Changed,Details,Timestamp\n")
        val logSdf = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault())
        for (log in logs) {
            val dateStr = logSdf.format(Date(log.timestamp))
            val detailSafe = log.details.replace("\"", "\"\"")
            csvBuilder.append("${log.logId},${log.itemId},\"${log.productName}\",${log.transactionType},${log.quantityChanged},\"$detailSafe\",\"$dateStr\"\n")
        }
        
        val content = csvBuilder.toString()
        val fileUriString = writeToDownloads(context, fileName, "text/csv", content.toByteArray())
        return fileUriString ?: "Export failed"
    }

    fun exportToPDF(
        context: Context,
        items: List<InventoryItem>,
        periodLogs: List<AuditLogEntry> = emptyList(),
        periodTitle: String = "All Time"
    ): String {
        val sdf = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault())
        val timestamp = sdf.format(Date())
        val fileName = "Polwel_Report_$timestamp.pdf"
        
        val pdfDocument = PdfDocument()
        
        val baseTypeface = Typeface.create(Typeface.SERIF, Typeface.NORMAL)
        val boldTypeface = Typeface.create(Typeface.SERIF, Typeface.BOLD)
        val banglaTypeface = try {
            Typeface.createFromAsset(context.assets, "fonts/sutonny_mj.ttf")
        } catch(e: Exception) {
            baseTypeface
        }
        val banglaBoldTypeface = Typeface.create(banglaTypeface, Typeface.BOLD)
        
        // A4 Paper Dimensions in Points: Width = 595, Height = 842
        val pageWidth = 595
        val pageHeight = 842
        val pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, 1).create()
        val page = pdfDocument.startPage(pageInfo)
        
        val canvas: Canvas = page.canvas
        val paint = Paint()
        
        // 1. Background Fill - Strict white for optimal B&W printing (saving ink/toner)
        canvas.drawColor(Color.WHITE)
        
        // Draw Header Border with a clean thin charcoal accent line
        paint.color = Color.BLACK
        paint.style = Paint.Style.STROKE
        paint.strokeWidth = 1f
        canvas.drawRect(20f, 20f, (pageWidth - 20).toFloat(), 130f, paint)
        
        // Reset paint style
        paint.style = Paint.Style.FILL
        
        // 2. Title Typography - High-contrast black/charcoal
        paint.color = Color.BLACK
        paint.textSize = 20f
        paint.isAntiAlias = true
        paint.typeface = boldTypeface
        canvas.drawText("GLASSLOG INVENTORY", 30f, 50f, paint)
        
        paint.textSize = 10f
        paint.typeface = baseTypeface
        canvas.drawText("Enterprise Resource Management System", 30f, 70f, paint)
        
        canvas.drawText("Developed by Khalid Hasan Limon", 30f, 90f, paint)
        
        // Generation Date Indicator
        paint.textSize = 9f
        canvas.drawText("Report Generated: " + SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(Date()) + " | Period: $periodTitle", 30f, 115f, paint)
        
        // Drawing Summary Metrics inside Box
        val totalValuation = items.sumOf { it.currentStock * it.cost }
        paint.color = Color.BLACK
        paint.textSize = 11f
        paint.typeface = boldTypeface
        canvas.drawText("TOTAL VALUE: ৳${String.format(Locale.US, "%.2f", totalValuation)}", (pageWidth - 230).toFloat(), 50f, paint)
        
        paint.typeface = baseTypeface
        paint.textSize = 10f
        canvas.drawText("Total Unique SKUs: ${items.size}", (pageWidth - 230).toFloat(), 75f, paint)
        canvas.drawText("Total Items Instock: ${items.sumOf { it.currentStock }}", (pageWidth - 230).toFloat(), 95f, paint)
        
        // 3. Table Column Headers
        val startY = 150f
        
        // MS Word Border=1 Settings
        val col1 = 20f
        val col2 = 175f
        val col3 = 275f
        val col4 = 375f
        val col5 = 445f
        val col6 = 510f
        val col7 = (pageWidth - 20).toFloat()
        
        paint.style = Paint.Style.FILL
        paint.color = Color.BLACK
        paint.textSize = 10f
        paint.typeface = boldTypeface
        
        canvas.drawText("NAME", col1 + 5f, startY + 16f, paint)
        canvas.drawText("SKU", col2 + 5f, startY + 16f, paint)
        canvas.drawText("CATEGORY", col3 + 5f, startY + 16f, paint)
        canvas.drawText("STOCK", col4 + 5f, startY + 16f, paint)
        canvas.drawText("COST", col5 + 5f, startY + 16f, paint)
        canvas.drawText("TOTAL", col6 + 5f, startY + 16f, paint)
        
        paint.typeface = banglaTypeface
        paint.textSize = 10f
        
        var currentY = startY + 25f
        val maxRowsOnPage = 18
        val limitedItems = items.take(maxRowsOnPage) // Keep report neat on first page
        
        // Draw top horizontal line for header
        paint.style = Paint.Style.STROKE
        paint.strokeWidth = 1f
        canvas.drawLine(col1, startY, col7, startY, paint)
        canvas.drawLine(col1, currentY, col7, currentY, paint)
        
        for ((index, item) in limitedItems.withIndex()) {
            paint.style = Paint.Style.FILL
            paint.color = Color.BLACK 
            currentY += 21f
            
            // Name auto-truncating elegant formatting
            val displayName = if (item.name.length > 20) item.name.substring(0, 17) + "..." else item.name
            canvas.drawText(displayName, col1 + 5f, currentY - 5f, paint)
            canvas.drawText(item.sku, col2 + 5f, currentY - 5f, paint)
            canvas.drawText(item.category, col3 + 5f, currentY - 5f, paint)
            
            // Bold stock indicator if stock is very low
            if (item.currentStock <= 5) {
                paint.typeface = banglaBoldTypeface
            }
            canvas.drawText(item.currentStock.toString(), col4 + 5f, currentY - 5f, paint)
            paint.typeface = banglaTypeface
            
            canvas.drawText("৳${String.format(Locale.US, "%.2f", item.cost)}", col5 + 5f, currentY - 5f, paint)
            
            val totalValue = item.currentStock * item.cost
            paint.typeface = banglaBoldTypeface
            canvas.drawText("৳${String.format(Locale.US, "%.2f", totalValue)}", col6 + 5f, currentY - 5f, paint)
            paint.typeface = banglaTypeface
            
            // Draw horizontal line below item cell
            paint.style = Paint.Style.STROKE
            canvas.drawLine(col1, currentY, col7, currentY, paint)
        }
        
        // Draw Vertical Border Lines for table grid
        paint.style = Paint.Style.STROKE
        canvas.drawRect(col1, startY, col7, currentY, paint)
        canvas.drawLine(col2, startY, col2, currentY, paint)
        canvas.drawLine(col3, startY, col3, currentY, paint)
        canvas.drawLine(col4, startY, col4, currentY, paint)
        canvas.drawLine(col5, startY, col5, currentY, paint)
        canvas.drawLine(col6, startY, col6, currentY, paint)
        
        paint.style = Paint.Style.FILL
        
        // 5. Draw simple bar chart for category stock distributions
        val categoryStocks = items.groupBy { it.category }
            .mapValues { it.value.sumOf { item -> item.currentStock } }
            .toList()
            .sortedByDescending { it.second }
            .take(5) // Top 5 categories
        
        if (categoryStocks.isNotEmpty()) {
            val maxStock = categoryStocks.maxOf { it.second }.toFloat()
            val chartStartY = currentY + 45f
            val chartHeight = 110f
            val chartStartX = 40f
            val chartWidth = (pageWidth - 80).toFloat()
            val maxBarHeight = chartHeight - 20f
            val barSpacing = chartWidth / categoryStocks.size
            val barWidth = barSpacing * 0.5f // Adjusted for generous spacing
            
            // Graph Title & Header
            paint.color = Color.parseColor("#0F172A")
            paint.textSize = 10.5f
            paint.typeface = Typeface.create(Typeface.SERIF, Typeface.BOLD)
            canvas.drawText("CATEGORY STOCK DISTRIBUTION (TOP 5)", chartStartX, chartStartY - 15f, paint)
            
            // Y-Axis Horizontal Guide Lines
            paint.strokeWidth = 0.5f
            paint.color = Color.parseColor("#E2E8F0")
            for (i in 0..4 step 2) {
                val gridY = chartStartY + (chartHeight * i / 4)
                canvas.drawLine(chartStartX, gridY, chartStartX + chartWidth, gridY, paint)
            }
            
            // X & Y Axis Base Guide Lines
            paint.strokeWidth = 1.2f
            paint.color = Color.parseColor("#64748B")
            canvas.drawLine(chartStartX, chartStartY, chartStartX, chartStartY + chartHeight, paint) // Y-Axis
            canvas.drawLine(chartStartX, chartStartY + chartHeight, chartStartX + chartWidth, chartStartY + chartHeight, paint) // X-Axis
            
            paint.style = Paint.Style.FILL
            
            for ((idx, categoryPair) in categoryStocks.withIndex()) {
                val categoryName = categoryPair.first
                val categoryVal = categoryPair.second
                
                val normalizedHeight = if (maxStock > 0f) (categoryVal / maxStock) * maxBarHeight else 0f
                
                val startX = chartStartX + (idx * barSpacing) + (barSpacing - barWidth) / 2
                val topY = chartStartY + chartHeight - normalizedHeight
                
                // Draw bar using aesthetic modern fill
                paint.color = Color.parseColor("#38BDF8") // Subtle sky blue tint for PDF compatibility
                canvas.drawRect(startX, topY, startX + barWidth, chartStartY + chartHeight, paint)
                
                // Draw category value (Top of bar)
                paint.color = Color.parseColor("#0F172A")
                paint.textSize = 8.5f
                paint.typeface = Typeface.create(Typeface.SERIF, Typeface.BOLD)
                canvas.drawText(categoryVal.toString(), startX + barWidth / 3f, topY - 5f, paint)
                
                // Draw category name (Below X-Axis)
                paint.typeface = Typeface.create(Typeface.SERIF, Typeface.NORMAL)
                paint.color = Color.parseColor("#475569")
                val shortName = if (categoryName.length > 12) categoryName.substring(0, 10) + ".." else categoryName
                canvas.drawText(shortName, startX, chartStartY + chartHeight + 14f, paint)
            }
        }
        
        // 4. Footer Branding & Attribution (Extremely elegant footer)
        paint.color = Color.parseColor("#475569")
        paint.strokeWidth = 0.8f
        paint.style = Paint.Style.STROKE
        canvas.drawLine(20f, (pageHeight - 50).toFloat(), (pageWidth - 20).toFloat(), (pageHeight - 50).toFloat(), paint)
        paint.style = Paint.Style.FILL
        
        paint.color = Color.parseColor("#64748B")
        paint.textSize = 8.5f
        paint.typeface = Typeface.create(Typeface.SERIF, Typeface.NORMAL)
        canvas.drawText(
            "Generated by Polwel Inventory | Khalid Hasan Limon",
            35f,
            (pageHeight - 35).toFloat(),
            paint
        )
        
        val pageCountText = "Page 1 of " + (if (periodLogs.isNotEmpty()) "2" else "1")
        canvas.drawText(
            pageCountText,
            (pageWidth - 75).toFloat(),
            (pageHeight - 35).toFloat(),
            paint
        )
        
        pdfDocument.finishPage(page)

        if (periodLogs.isNotEmpty()) {
            val pageInfo2 = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, 2).create()
            val page2 = pdfDocument.startPage(pageInfo2)
            val canvas2: Canvas = page2.canvas
            val paint2 = Paint()
            
            canvas2.drawColor(Color.WHITE)
            
            paint2.color = Color.BLACK
            paint2.textSize = 16f
            paint2.isAntiAlias = true
            paint2.typeface = boldTypeface
            canvas2.drawText("AUDIT TRANSACTION LOGS ($periodTitle)", 40f, 60f, paint2)
            
            val startY2 = 100f
            
            // MS Word Style Table border lines settings
            val col1 = 20f
            val col2 = 110f
            val col3 = 210f
            val col4 = 260f
            val col5 = 310f
            val col6 = (pageWidth - 20).toFloat()
            
            paint2.color = Color.BLACK
            paint2.style = Paint.Style.STROKE
            paint2.strokeWidth = 1f
            // top line header
            canvas2.drawLine(col1, startY2, col6, startY2, paint2)
            
            paint2.style = Paint.Style.FILL
            paint2.textSize = 10f
            paint2.typeface = boldTypeface
            
            canvas2.drawText("DATE/TIME", col1 + 5f, startY2 + 16f, paint2)
            canvas2.drawText("PRODUCT", col2 + 5f, startY2 + 16f, paint2)
            canvas2.drawText("TYPE", col3 + 5f, startY2 + 16f, paint2)
            canvas2.drawText("QTY", col4 + 5f, startY2 + 16f, paint2)
            canvas2.drawText("DETAILS", col5 + 5f, startY2 + 16f, paint2)
            
            paint2.typeface = banglaTypeface
            paint2.textSize = 10f
            
            var currentY2 = startY2 + 25f
            val logSdf = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault())
            val logsPerPage = 32
            val chunkedLogs = if (periodLogs.isEmpty()) listOf(emptyList()) else periodLogs.chunked(logsPerPage)
            val totalPages = 1 + chunkedLogs.size

            chunkedLogs.forEachIndexed { index, chunk ->
                val pageNum = index + 2
                val page = if (index == 0) page2 else pdfDocument.startPage(PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNum).create())
                val canvas = if (index == 0) canvas2 else page.canvas

                if (index > 0) {
                    canvas.drawColor(Color.WHITE)
                    paint2.color = Color.BLACK
                    paint2.textSize = 16f
                    paint2.isAntiAlias = true
                    paint2.typeface = boldTypeface
                    canvas.drawText("AUDIT TRANSACTION LOGS ($periodTitle)", 40f, 60f, paint2)
                    
                    paint2.strokeWidth = 1f
                    paint2.style = Paint.Style.STROKE
                    canvas.drawLine(col1, startY2, col6, startY2, paint2)
                    
                    paint2.style = Paint.Style.FILL
                    paint2.textSize = 10f
                    paint2.typeface = boldTypeface
                    canvas.drawText("DATE/TIME", col1 + 5f, startY2 + 16f, paint2)
                    canvas.drawText("PRODUCT", col2 + 5f, startY2 + 16f, paint2)
                    canvas.drawText("TYPE", col3 + 5f, startY2 + 16f, paint2)
                    canvas.drawText("QTY", col4 + 5f, startY2 + 16f, paint2)
                    canvas.drawText("DETAILS", col5 + 5f, startY2 + 16f, paint2)
                }

                var currentY = startY2 + 25f
                paint2.strokeWidth = 1f
                paint2.style = Paint.Style.STROKE
                canvas.drawLine(col1, currentY, col6, currentY, paint2)

                for (log in chunk) {
                    paint2.style = Paint.Style.FILL
                    paint2.color = Color.BLACK
                    currentY += 22f

                    val dateStr = logSdf.format(Date(log.timestamp))
                    paint2.typeface = baseTypeface
                    canvas.drawText(dateStr, col1 + 5f, currentY - 6f, paint2)

                    val shortSku = if (log.productName.length > 15) log.productName.substring(0, 13) + ".." else log.productName
                    paint2.typeface = if (shortSku.any { it.toInt() in 0x0980..0x09FF }) banglaTypeface else baseTypeface
                    canvas.drawText(shortSku, col2 + 5f, currentY - 6f, paint2)

                    paint2.typeface = baseTypeface
                    paint2.color = if (log.transactionType == "IN") Color.parseColor("#059669") else Color.parseColor("#E11D48")
                    canvas.drawText(log.transactionType, col3 + 5f, currentY - 6f, paint2)

                    paint2.color = Color.BLACK
                    val qtySign = if (log.transactionType == "IN") "+" else "-"
                    canvas.drawText("$qtySign${log.quantityChanged}", col4 + 5f, currentY - 6f, paint2)

                    val detailsStr = if (log.details.isBlank()) "None" else if (log.details.length > 45) log.details.substring(0, 42) + "..." else log.details
                    paint2.typeface = if (detailsStr.any { it.toInt() in 0x0980..0x09FF }) banglaTypeface else baseTypeface
                    canvas.drawText(detailsStr, col5 + 5f, currentY - 6f, paint2)

                    paint2.style = Paint.Style.STROKE
                    canvas.drawLine(col1, currentY, col6, currentY, paint2)
                }

                // Dynamic Vertical Borders per page
                paint2.style = Paint.Style.STROKE
                paint2.color = Color.BLACK
                canvas.drawRect(col1, startY2, col6, currentY, paint2)
                canvas.drawLine(col2, startY2, col2, currentY, paint2)
                canvas.drawLine(col3, startY2, col3, currentY, paint2)
                canvas.drawLine(col4, startY2, col4, currentY, paint2)
                canvas.drawLine(col5, startY2, col5, currentY, paint2)

                // Footer rendering
                paint2.strokeWidth = 0.8f
                canvas.drawLine(20f, (pageHeight - 50).toFloat(), (pageWidth - 20).toFloat(), (pageHeight - 50).toFloat(), paint2)
                paint2.style = Paint.Style.FILL
                paint2.textSize = 8.5f
                paint2.typeface = baseTypeface
                canvas.drawText("Generated by Polwel Inventory | Khalid Hasan Limon", 35f, (pageHeight - 35).toFloat(), paint2)
                canvas.drawText("Page $pageNum of $totalPages", (pageWidth - 75).toFloat(), (pageHeight - 35).toFloat(), paint2)

                pdfDocument.finishPage(page)
            }
        }
        
        val fileUriString = writePdfDocumentToDownloads(context, pdfDocument, fileName)
        pdfDocument.close()
        
        return fileUriString ?: "Export failed"
    }

    private fun writeToDownloads(
        context: Context,
        fileName: String,
        mimeType: String,
        data: ByteArray
    ): String? {
        if (BackupRestoreManager.hasStoragePermission(context)) {
            BackupRestoreManager.initializeDirectories()
            val targetFile = File(BackupRestoreManager.reportsDir, fileName)
            try {
                val out = FileOutputStream(targetFile)
                out.write(data)
                out.close()
                return targetFile.absolutePath
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }
        
        val resolver = context.contentResolver
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            val contentValues = ContentValues().apply {
                put(MediaStore.MediaColumns.DISPLAY_NAME, fileName)
                put(MediaStore.MediaColumns.MIME_TYPE, mimeType)
                put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS)
            }
            try {
                val uri = resolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, contentValues)
                if (uri != null) {
                    val outputStream: OutputStream? = resolver.openOutputStream(uri)
                    if (outputStream != null) {
                        outputStream.write(data)
                        outputStream.close()
                        return uri.toString()
                    }
                }
            } catch (e: Exception) {
                e.printStackTrace()
            }
        } else {
            // Android 9 and lower
            val downloadsDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
            if (!downloadsDir.exists()) {
                downloadsDir.mkdirs()
            }
            val targetFile = File(downloadsDir, fileName)
            try {
                val out = FileOutputStream(targetFile)
                out.write(data)
                out.close()
                return Uri.fromFile(targetFile).toString()
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }
        return null
    }

    private fun writePdfDocumentToDownloads(
        context: Context,
        pdfDocument: PdfDocument,
        fileName: String
    ): String? {
        if (BackupRestoreManager.hasStoragePermission(context)) {
            BackupRestoreManager.initializeDirectories()
            val targetFile = File(BackupRestoreManager.reportsDir, fileName)
            try {
                val out = FileOutputStream(targetFile)
                pdfDocument.writeTo(out)
                out.close()
                return targetFile.absolutePath
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }

        val resolver = context.contentResolver
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            val contentValues = ContentValues().apply {
                put(MediaStore.MediaColumns.DISPLAY_NAME, fileName)
                put(MediaStore.MediaColumns.MIME_TYPE, "application/pdf")
                put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS)
            }
            try {
                val uri = resolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, contentValues)
                if (uri != null) {
                    val outputStream: OutputStream? = resolver.openOutputStream(uri)
                    if (outputStream != null) {
                        pdfDocument.writeTo(outputStream)
                        outputStream.close()
                        return uri.toString()
                    }
                }
            } catch (e: Exception) {
                e.printStackTrace()
            }
        } else {
            val downloadsDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
            if (!downloadsDir.exists()) {
                downloadsDir.mkdirs()
            }
            val targetFile = File(downloadsDir, fileName)
            try {
                val out = FileOutputStream(targetFile)
                pdfDocument.writeTo(out)
                out.close()
                return Uri.fromFile(targetFile).toString()
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }
        return null
    }
}
