// Architected by Khalid Hasan Limon
package com.example.ui

import android.content.ContentValues
import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.net.Uri
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import com.example.data.AuditLogEntry
import com.example.data.InventoryItem
import java.io.File
import java.io.FileOutputStream
import java.io.OutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object ExportEngine {

    fun exportToCSV(
        context: Context,
        items: List<InventoryItem>,
        logs: List<AuditLogEntry>
    ): String {
        val sdf = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault())
        val timestamp = sdf.format(Date())
        val fileName = "GlassLog_Export_$timestamp.csv"
        
        val csvBuilder = StringBuilder()
        
        // 1. App Header & Attribution
        csvBuilder.append("GlassLog Inventory Enterprise Report\n")
        csvBuilder.append("Developed by Khalid Hasan Limon\n")
        csvBuilder.append("Generated Time,${SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(Date())}\n")
        csvBuilder.append("Export Footprint,Generated by GlassLog Inventory | Khalid Hasan Limon\n\n")
        
        // 2. Summary stats
        val totalItems = items.size
        val totalStock = items.sumOf { it.currentStock }
        val totalValuation = items.sumOf { it.currentStock * it.cost }
        csvBuilder.append("SUMMARY STATS\n")
        csvBuilder.append("Total Unique SKUs,$totalItems\n")
        csvBuilder.append("Total Current Stock,$totalStock\n")
        csvBuilder.append("Total Valuation,$${String.format(Locale.US, "%.2f", totalValuation)}\n\n")
        
        // 3. Inventory Table
        csvBuilder.append("CURRENT INVENTORY\n")
        csvBuilder.append("Item ID,Name,SKU,Category,Current Stock,Unit Cost,Total Value\n")
        for (item in items) {
            val totalValue = item.currentStock * item.cost
            csvBuilder.append("${item.itemId},\"${item.name}\",\"${item.sku}\",\"${item.category}\",${item.currentStock},${item.cost},${String.format(Locale.US, "%.2f", totalValue)}\n")
        }
        csvBuilder.append("\n")
        
        // 4. Audit Log Table
        csvBuilder.append("AUDIT LOG TRADING TRANSACTION LOGS\n")
        csvBuilder.append("Log ID,Item ID,SKU,Type (IN/OUT),Quantity Changed,Timestamp\n")
        val logSdf = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault())
        for (log in logs) {
            val dateStr = logSdf.format(Date(log.timestamp))
            csvBuilder.append("${log.logId},${log.itemId},\"${log.sku}\",${log.transactionType},${log.quantityChanged},\"$dateStr\"\n")
        }
        
        val content = csvBuilder.toString()
        val fileUriString = writeToDownloads(context, fileName, "text/csv", content.toByteArray())
        return fileUriString ?: "Export failed"
    }

    fun exportToPDF(
        context: Context,
        items: List<InventoryItem>
    ): String {
        val sdf = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault())
        val timestamp = sdf.format(Date())
        val fileName = "GlassLog_Report_$timestamp.pdf"
        
        val pdfDocument = PdfDocument()
        
        // Create a single page detailing stock layout (standard letter/A4 style canvas sizing)
        val pageWidth = 595 // A4 width in points
        val pageHeight = 842 // A4 height in points
        val pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, 1).create()
        val page = pdfDocument.startPage(pageInfo)
        
        val canvas: Canvas = page.canvas
        val paint = Paint()
        
        // 1. Background Fill (Authoritative deep styling - True Black header, extremely clean crisp text)
        canvas.drawColor(Color.parseColor("#0F172A")) // Slate navy deep background
        
        // Draw Header Glass Container Background
        paint.color = Color.parseColor("#1E293B")
        canvas.drawRect(20f, 20f, (pageWidth - 20).toFloat(), 130f, paint)
        
        // Glowing cyan accent line under header
        paint.color = Color.parseColor("#00E5FF")
        paint.strokeWidth = 3f
        canvas.drawLine(20f, 130f, (pageWidth - 20).toFloat(), 130f, paint)
        
        // 2. Title Typography (Serif styling painted)
        paint.color = Color.WHITE
        paint.textSize = 20f
        paint.isAntiAlias = true
        paint.typeface = Typeface.create(Typeface.SERIF, Typeface.BOLD)
        canvas.drawText("GLASSLOG INVENTORY", 40f, 60f, paint)
        
        paint.color = Color.parseColor("#94A3B8")
        paint.textSize = 10f
        paint.typeface = Typeface.create(Typeface.SERIF, Typeface.NORMAL)
        canvas.drawText("Enterprise Resource Management System", 40f, 80f, paint)
        canvas.drawText("Developed by Khalid Hasan Limon", 40f, 95f, paint)
        
        // Date
        paint.color = Color.parseColor("#38BDF8")
        paint.textSize = 9f
        canvas.drawText("Report Generated: " + SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(Date()), 40f, 115f, paint)
        
        // Metrics Summary
        val totalValuation = items.sumOf { it.currentStock * it.cost }
        paint.color = Color.WHITE
        paint.textSize = 12f
        paint.typeface = Typeface.create(Typeface.SERIF, Typeface.BOLD)
        canvas.drawText("TOTAL VALUE: $${String.format(Locale.US, "%.2f", totalValuation)}", (pageWidth - 250).toFloat(), 60f, paint)
        
        paint.typeface = Typeface.create(Typeface.SERIF, Typeface.NORMAL)
        paint.textSize = 10f
        paint.color = Color.parseColor("#94A3B8")
        canvas.drawText("Total Unique SKUs: ${items.size}", (pageWidth - 250).toFloat(), 80f, paint)
        canvas.drawText("Total Items Instock: ${items.sumOf { it.currentStock }}", (pageWidth - 250).toFloat(), 100f, paint)
        
        // 3. Table Column Headers
        val startY = 160f
        paint.color = Color.parseColor("#334155") // Frosted slate header row
        canvas.drawRect(20f, startY, (pageWidth - 20).toFloat(), startY + 25f, paint)
        
        paint.color = Color.parseColor("#38BDF8") // Ice blue text
        paint.textSize = 10f
        paint.typeface = Typeface.create(Typeface.SERIF, Typeface.BOLD)
        
        canvas.drawText("NAME", 35f, startY + 16f, paint)
        canvas.drawText("SKU", 185f, startY + 16f, paint)
        canvas.drawText("CATEGORY", 285f, startY + 16f, paint)
        canvas.drawText("STOCK", 395f, startY + 16f, paint)
        canvas.drawText("COST", 455f, startY + 16f, paint)
        canvas.drawText("TOTAL", 515f, startY + 16f, paint)
        
        // Draw Row Items
        paint.typeface = Typeface.create(Typeface.SERIF, Typeface.NORMAL)
        paint.color = Color.WHITE
        paint.textSize = 9f
        
        var currentY = startY + 25f
        val maxRowsOnPage = 28
        val limitedItems = items.take(maxRowsOnPage) // Keep report neat on first page
        
        for ((index, item) in limitedItems.withIndex()) {
            currentY += 20f
            // Draw alternating row background
            if (index % 2 == 1) {
                paint.color = Color.parseColor("#1E293B")
                canvas.drawRect(20f, currentY - 14f, (pageWidth - 20).toFloat(), currentY + 6f, paint)
            }
            
            paint.color = Color.WHITE
            // Name (ellipsize if too long)
            val displayName = if (item.name.length > 20) item.name.substring(0, 17) + "..." else item.name
            canvas.drawText(displayName, 35f, currentY, paint)
            canvas.drawText(item.sku, 185f, currentY, paint)
            canvas.drawText(item.category, 285f, currentY, paint)
            canvas.drawText(item.currentStock.toString(), 395f, currentY, paint)
            canvas.drawText("$${String.format(Locale.US, "%.2f", item.cost)}", 455f, currentY, paint)
            
            val totalValue = item.currentStock * item.cost
            canvas.drawText("$${String.format(Locale.US, "%.2f", totalValue)}", 515f, currentY, paint)
        }
        
        // 4. Footer Branding & Attribution (Extremely elegant footer)
        paint.color = Color.parseColor("#64748B")
        paint.strokeWidth = 1f
        canvas.drawLine(20f, (pageHeight - 50).toFloat(), (pageWidth - 20).toFloat(), (pageHeight - 50).toFloat(), paint)
        
        paint.textSize = 8.5f
        paint.typeface = Typeface.create(Typeface.SERIF, Typeface.NORMAL)
        canvas.drawText(
            "Generated by GlassLog Inventory | Khalid Hasan Limon",
            35f,
            (pageHeight - 35).toFloat(),
            paint
        )
        
        val pageCountText = "Page 1 of 1"
        canvas.drawText(
            pageCountText,
            (pageWidth - 75).toFloat(),
            (pageHeight - 35).toFloat(),
            paint
        )
        
        pdfDocument.finishPage(page)
        
        val fileUriString = writePdfDocumentToDownloads(context, pdfDocument, fileName)
        pdfDocument.close()
        
        return fileUriString ?: "Export failed"
    }

    private fun writeToDownloads(
        context: Context,
        fileName: String,
        mimeType: String,
        data: ByteArray
    ): String? {
        val resolver = context.contentResolver
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            val contentValues = ContentValues().apply {
                put(MediaStore.MediaColumns.DISPLAY_NAME, fileName)
                put(MediaStore.MediaColumns.MIME_TYPE, mimeType)
                put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS)
            }
            try {
                val uri = resolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, contentValues)
                if (uri != null) {
                    val outputStream: OutputStream? = resolver.openOutputStream(uri)
                    if (outputStream != null) {
                        outputStream.write(data)
                        outputStream.close()
                        return uri.toString()
                    }
                }
            } catch (e: Exception) {
                e.printStackTrace()
            }
        } else {
            // Android 9 and lower
            val downloadsDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
            if (!downloadsDir.exists()) {
                downloadsDir.mkdirs()
            }
            val targetFile = File(downloadsDir, fileName)
            try {
                val out = FileOutputStream(targetFile)
                out.write(data)
                out.close()
                return Uri.fromFile(targetFile).toString()
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }
        return null
    }

    private fun writePdfDocumentToDownloads(
        context: Context,
        pdfDocument: PdfDocument,
        fileName: String
    ): String? {
        val resolver = context.contentResolver
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            val contentValues = ContentValues().apply {
                put(MediaStore.MediaColumns.DISPLAY_NAME, fileName)
                put(MediaStore.MediaColumns.MIME_TYPE, "application/pdf")
                put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS)
            }
            try {
                val uri = resolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, contentValues)
                if (uri != null) {
                    val outputStream: OutputStream? = resolver.openOutputStream(uri)
                    if (outputStream != null) {
                        pdfDocument.writeTo(outputStream)
                        outputStream.close()
                        return uri.toString()
                    }
                }
            } catch (e: Exception) {
                e.printStackTrace()
            }
        } else {
            val downloadsDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
            if (!downloadsDir.exists()) {
                downloadsDir.mkdirs()
            }
            val targetFile = File(downloadsDir, fileName)
            try {
                val out = FileOutputStream(targetFile)
                pdfDocument.writeTo(out)
                out.close()
                return Uri.fromFile(targetFile).toString()
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }
        return null
    }
}
